### ISSUE TITLE
Problem using Landscape analysis on Windows (Python)

### ISSUE THREAD

**Issue by gislfzhao** [martibosch/pylandstats#10]
* PyLandStats version: 2.2.1
* Python version: 3.6
* Operating System: Windows

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I am using the pylandstats library to solve the landscape index, and the following prompt appears after running.
![image](https://user-images.githubusercontent.com/32775389/105697205-3dd6d580-5f3f-11eb-9ae5-edcf64e1ccb5.png)

C:\Users\GISzhao\AppData\Local\Programs\Python\Python36\python36.exe C:/Users/GISzhao/Desktop/MyGraduate/MyMaster/03_GeoSimulation_CA/code/temp.py
WARNING: Module C:\Users\GISzhao\AppData\Local\Programs\Python\Python36\lib\site-packages\pylandstats\landscape.py has not been compiled for Transonic-Numba

I want to know what is the reason for this and how to solve it.

`from pylandstats import Landscape

tif_file = '../test/data/lucc2015.tif'
landscape = Landscape(tif_file)
df = landscape.compute_landscape_metrics_df()
print(df)
print(df.columns)`
This is the code I am running.

Thank you.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by martibosch** [comment]
Hello @gislfzhao,

thank you for using pylandstats and raising this issue. I believe this is the same as #4 and #5. What are your versions of the `numba` and `transonic` packages?

Also, this comment might be of help: https://github.com/martibosch/pylandstats/issues/4#issuecomment-678748304

Best,
Martí

**Comment by martibosch** [comment]
Well I will be closing this since it seems to boil down to essentially #4 and #5 , but @gislfzhao do not hesitate to reopen if you find something new.

Best,
Martí
