### ISSUE TITLE
No attribute read_geotiff

### ISSUE THREAD

**Issue by aazuspan** [martibosch/pylandstats#18]
* PyLandStats version: `2.3.0`
* Python version: `3.8`
* Operating System: `Windows 10`

### Description
Hi @martibosch, `pylandstats` is a great package. I just found a small error in the readme.

The `read_geotiff` function used in the first [readme example](https://github.com/martibosch/pylandstats#features) no longer works. I got it to work by instantiating a `Landscape` instead.

### What I Did

```python
>>> import pylandstats as pls
>>> ls = pls.read_geotiff('data/vaud_g100_clc00_V18_5.tif')

AttributeError: module 'pylandstats' has no attribute 'read_geotiff'
```

**Comment by martibosch** [comment]
Hello @aazuspan,

thank you for using pylandstats and for reporting this. Sorry for the delay in my response. I have amended the README in [996b0b4](https://github.com/martibosch/pylandstats/commit/996b0b4da02262aa83e5ff639b257db46a54af91).

Closing this :smile:
