### ISSUE TITLE
zonal analysis (03-zonal-analysis.ipynb) -"TypeError: expected string or bytes-like object"

### ISSUE THREAD

**Issue by Baharehfa** [martibosch/pylandstats#19]
* PyLandStats version: Latest
* Python version: 3.9.7
* Operating System: Windows 10 x64

Hi Marti, 

Thanks for creating the Pylandstat. I have calculated the metrics and now I am trying to do the zonal analysis (03-zonal-analysis.ipynb) but I received the following error: "TypeError: expected string or bytes-like object". I wanted to make sure the problem is not with my map therefore,  I copied and pasted the code with the vaud_g100_clc00_V18_5 and bern_valais_g100_clc00 maps that you used in Pylandstat and realized that we received the same error.  

I would appreciate it if you could help to resolve the error. 

Best, 
Bahareh

<img width="457" alt="2022-04-12 (2)" src="https://user-images.githubusercontent.com/51041177/163065095-01e58a15-7faa-413e-8a1b-526b5f5e26ac.png">

**Comment by martibosch** [comment]
Hello! I am not sure what raised your error but it will probably go away if you use pylandstats v3 and geopandas>=1. Feel free to reopen otherwise.
