### ISSUE TITLE
PyLandStats does not install on M1 MacBook using Anaconda

### ISSUE THREAD

**Issue by billyhales** [martibosch/pylandstats#20]
* PyLandStats version: 2.4.2
* Python version: 3.10.5
* Operating System: MacOS 12.4 Monterey (Apple Silicon M1)

### Description

Describe what you were trying to get done.
I was attempting to install pylandstats, but could not via conda. 

Tell us what happened, what went wrong, and what you expected to happen.
It failed to install with fixed solve and flexible solve. It seems to not be listed in the architecture osx-arm64 and noarch channels (error #1).

### What I Did
The only way I could get it to installl with via pip. However, it would give a message indicating that landscape.py failed to compile for transonic-pythian (error #2).

```
Paste the command(s) you ran and the output.
and use the search bar at the top of the page.

<!--Error #1-->
(model_studies) billyhales@ ~ % conda install -c conda-forge pylandstats
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pylandstats

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

<!--Error #2-->
>>> import pylandstats
Module /Users/billyhales/miniforge3/envs/model_studies/lib/python3.10/site-packages/pylandstats/landscape.py has not been compiled for Transonic-Pythran

If there was a crash, please include the traceback here.
```

**Comment by martibosch** [comment]
Hello! i think this shouldn’t happen in v2.4.2 but in any case you can certainly install v3 directly from conda forge. Also the pythran warning should go away. Otherwise feel free to reopen.
