### ISSUE TITLE
Landscape.py has not been compiled for Transonic-Numba

### ISSUE THREAD

**Issue by JasperSTV** [martibosch/pylandstats#21]
Hi Marti, 

First, I want to thank you for creating Pylandstats because it is great having a package in Python for calculating landscape metrics. 

Nevertheless, ever since I have been using Pylandstats, I have received the error "...\lib\site-packages\pylandstats\landscape.py has not been compiled for Transonic-Numba.". This is an error you have seen pass by on the Github here multiple times. 

Usually, I have been using your package for smaller or far coarser datasets, so the significantly increased time it took to calculate some metrics could be overseen. However, currently I am using a dataset of about 210 hectares, and it takes approximately 30min/hectare to calculate all landscape metrics.

I was wondering whether recently you have gained more insight into factor that creates this warning for Windows computers, and how it can potentially be solved. If you require any additional information, I will gladly provide it. I hope to hear from you, and thank you again!

Cheers,

Jasper

**Comment by martibosch** [comment]
Hello! pylandstats v3 addresses many performance issues so hopefully it should work much better for your use cases. Also the pythran warning should no longer appear.
