### ISSUE TITLE
 warnning when  import pylandstats

### ISSUE THREAD

**Issue by guof2019** [martibosch/pylandstats#4]
Dear sir,
When I run import pylandstats as pls in pycharm, it shows warnning. Module C:\Softwares\20.Python\Lib\site-packages\pylandstats\landscape.py has not been compiled for Transonic-Numba.
What does it mean and how should I solve this problem?
Thanks for your help.

**Comment by martibosch** [comment]
in order to address this, I'd need more information about your environment. There actually is [an issue template to report bugs in this repository](https://github.com/martibosch/pylandstats/blob/master/.github/ISSUE_TEMPLATES/bug.md). Additionally, could you provide more information about your Python environment, e.g., if you are using conda, could you paste the output of running `conda env export`?

Best,
Martí

**Comment by Yasharjamei** [comment]
Hi Marti;

Ive recently facing the same issue;

Python 3.7 Pylandstasts the latest version and 2.0.1

When I run the code on my windows 10 I face this error: \landscape.py has not been compiled for Transonic-Numba.

I used to work with this library few days ago and I recently faced this issue

**Comment by Yasharjamei** [comment]
Thanks, Marti for the comprehensive and great reply;

I will let you know if any issue arise in the future;

Cheers

**Comment by martibosch** [comment]
Thank you @Yasharjamei, I am then closing this for now. Feel free to reopen if needed. Best,

Martí

**Comment by ffrosch** [comment]
Hi, I discovered that the conda-repository does not contain a `__numba__`. I think transonic should compile this folder on-the-fly, but in my case it does not.

An easy fix is to run `transonic landscape.py -b numba` within the pylandstats package folder. Of course it is necessary to activate the respective conda environment before running the command.

Would it be possible to provide a pre-compiled `__numba__` folder with the conda package?

Best,
Florian

**Comment by jingliu0217** [comment]
Dear Sir,
This warning will still appear after I change the conda environment. Is there any other solution for it? 
Another question, will this warning affect the precession speed?
cheers

**Comment by sacridini** [comment]
It worked for me just installing numba with "pip install numba"
