### ISSUE TITLE
Warning message for contagion

### ISSUE THREAD

**Issue by kareed1** [martibosch/pylandstats#48]
Hello,

Thank you for putting together such a useful package. I had a question regarding the Contagion metric. When using the metric, I receive the warning "RuntimeWarning: Entropy-based metrics can only be computed in landscapes with more than two classes of patches. Returning nan". Should it say "two or more" classes instead of "more than two"? Pylandstats provides a value for Contagion when there are two classes.

**Comment by martibosch** [comment]
Hello @kareed1,

this is indeed a mistake, thank you for pointing it out. I have fixed it in [1ce4a4e](https://github.com/martibosch/pylandstats/commit/1ce4a4e764a0ff10b25cb066dc8bf26a7676ae97).

Best,
Martí
